### ISSUE TITLE
Imports will be helpful in README.md

### ISSUE THREAD

**Issue by siddhartha-gadgil** [dominique-unruh/scala-isabelle#2]
It would be useful to add the following at the beginning of the example (I was running in an ammonite REPL). The full name `de.unruh.isabelle.pure` is needed due to clash with `isabelle.control.isabelle`.

```scala
import de.unruh._, isabelle.control._
import de.unruh.isabelle.pure._
import java.nio.file._
implicit val ec: scala.concurrent.ExecutionContext = scala.concurrent.ExecutionContext.global
```

**Comment by dominique-unruh** [comment]
I added the imports from the full example (Example.java). I hope that works fine.
