### ISSUE TITLE
Inconsistent behaviors of sledgehammer

### ISSUE THREAD

**Issue by Lizn-zn** [dominique-unruh/scala-isabelle#9]
Thanks for the nice tool, and it works very well before I met this problem. 

I am trying to prove the following theorem using the sledgehammer. 

```
theory Test imports Main HOL.HOL HOL.Real Complex_Main  
begin
theorem fixes r :: real assumes r: "r >= 0" and "r^3 = 8" 
shows "r = 2"
proof-
  have eq1: "r = root 3 8" using assms sledgehammer 
  by (simp add: real_root_pos_unique) 
  show ?thesis sledgehammer
  by (simp add: eq1) 
qed 
```

This simple theorem can be proved when using vscode isabelle plugin; while it failed for `normal_with_Sledgehammern`. 
The theorem proving is conducted on the same machine, and I have set 
`[("provers", "cvc4 vampire verit e spass z3 zipperposition"),("timeout","60"),("verbose","true")]`

Is there something I didn't do properly?

**Comment by dominique-unruh** [comment]
I am not sure how this is connected to scala-isabelle. Are you invoking sledgehammer through scala-isabelle? If so, how?

**Comment by Lizn-zn** [comment]
I write a python interface (implemented based on pyspark) to interact with scala-isabelle. The sledgehammer is invoked by calling [ `normal_with_Sledgehammer`](https://github.com/dominique-unruh/scala-isabelle/blob/master/src/test/scala/de/unruh/isabelle/experiments/SledgehammerExperiment.scala).
But this theorem cannot be proved in this way (but can be proved when using vscode isabelle2021 plugin).

**Comment by Lizn-zn** [comment]
Sorry Dominique. I've identified that this error is due to my inconsistent implementation. Specifically, when working with scala-isabelle, I followed the Isabelle user guide to run `apply(auto)` before invoking sledgehammer. However, I did not apply this strategy when using the Isabelle plugin. I apologize for this oversight, and I genuinely appreciate this nice tool.
